name: '⚙️ Setup node'

description: 'Setup node with project version and install dependencies'

inputs:
  version:
    description: 'Node version to use'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install pnpm 📦
      uses: pnpm/action-setup@v4
    - name: Cache Dependencies ⌛️
      uses: actions/cache@v4
      id: cache-node-modules
      with:
        path: |
          ~/.pnpm-store
          node_modules
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('.github/actions/setup-node/action.yml') }}-node-${{ hashFiles('.nvmrc') }}-${{ inputs.version }}
    - name: Setup Node ⚙️
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.version }}
        node-version-file: '.nvmrc'
        cache: 'pnpm'
    - name: Install dependencies 📥
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
      run: pnpm install --frozen-lockfile
