export const DEFAULT_ROLES = {
  ADMIN: 'admin',
  USER: 'user',
};

export const DEFAULT_PERMISSIONS = {
  // User permissions
  USERS_CREATE: 'users:create',
  USERS_READ: 'users:read',
  USERS_UPDATE: 'users:update',
  USERS_DELETE: 'users:delete',

  // Role permissions
  ROLES_CREATE: 'roles:create',
  ROLES_READ: 'roles:read',
  ROLES_UPDATE: 'roles:update',
  ROLES_DELETE: 'roles:delete',

  // Permission permissions
  PERMISSIONS_CREATE: 'permissions:create',
  PERMISSIONS_READ: 'permissions:read',
  PERMISSIONS_UPDATE: 'permissions:update',
  PERMISSIONS_DELETE: 'permissions:delete',
};

export const ROLE_PERMISSIONS = {
  [DEFAULT_ROLES.ADMIN]: [
    DEFAULT_PERMISSIONS.USERS_CREATE,
    DEFAULT_PERMISSIONS.USERS_READ,
    DEFAULT_PERMISSIONS.USERS_UPDATE,
    DEFAULT_PERMISSIONS.USERS_DELETE,
    DEFAULT_PERMISSIONS.ROLES_CREATE,
    DEFAULT_PERMISSIONS.ROLES_READ,
    DEFAULT_PERMISSIONS.ROLES_UPDATE,
    DEFAULT_PERMISSIONS.ROLES_DELETE,
    DEFAULT_PERMISSIONS.PERMISSIONS_CREATE,
    DEFAULT_PERMISSIONS.PERMISSIONS_READ,
    DEFAULT_PERMISSIONS.PERMISSIONS_UPDATE,
    DEFAULT_PERMISSIONS.PERMISSIONS_DELETE,
  ],
  [DEFAULT_ROLES.USER]: [
    DEFAULT_PERMISSIONS.USERS_READ,
    // DEFAULT_PERMISSIONS.USERS_UPDATE,
  ],
};
