name: '✅ Todo to issue'

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v5
      - name: 'TODO to Issue'
        uses: 'alstr/todo-to-issue-action@v5'
        with:
          ISSUE_TEMPLATE: |
            ##  ✅ Codebase TODO  ✅

            ### **📝 Title**: {{ title }}

            ### **🔎 Details**

            {{ body }}
            {{ url }}
            {{ snippet }}
          AUTO_ASSIGN: true
          IGNORE: '.github/workflows/todo-to-issue.yml'
